#!/usr/bin/env python3
"""
内容重组引擎 (Content Repurposer)
将一篇长文(如博客/白皮书)自动拆解重组为多平台社媒矩阵内容
集成 LLM 引擎，实现真正的智能重组
"""

import argparse
import os
import json
from datetime import datetime
from llm_utils import call_llm

REPURPOSE_TEMPLATE = """
# 🔄 智能内容重组矩阵 (Content Repurposing Matrix)

**源文件**: {source_file}
**重组时间**: {date}

---

## 👔 LinkedIn (专业深度)
*目标: 建立思想领导力，引发行业讨论*

### Post 1: 核心洞察 (The Hook)
{linkedin_post_1}

### Post 2: 数据/案例支撑 (The Proof)
{linkedin_post_2}

---

## 🐦 X / Twitter (短平快)
*目标: 快速传播，制造话题*

### Thread (推文串)
{twitter_thread}

---

## 🎵 抖音 / TikTok (视觉化脚本)
*目标: 完播率，吸引泛人群*

### 视频脚本 (30-60秒)
**[Hook/前3秒]**: {tiktok_hook}
**[画面提示]**: {tiktok_visual}
**[口播文案]**: 
{tiktok_script}
**[CTA]**: {tiktok_cta}

---

## 📕 小红书 (图文种草)
*目标: 收藏与转化*

**[标题]**: {xiaohongshu_title}
**[正文]**: 
{xiaohongshu_body}
**[建议配图]**: {xiaohongshu_images}

---
*Generated by Super Marketing Pro v3.0 (LLM Powered)*
"""

def read_source_file(file_path):
    """读取源文件内容"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        print(f"❌ 读取文件失败: {str(e)}")
        return None

def repurpose_content(source_text):
    """使用 LLM 重组内容"""
    system_prompt = """你是一个顶级的内容营销总监。你的任务是将用户提供的长文（如博客、白皮书）重组(Repurpose)为不同社交平台的内容。
必须返回严格的 JSON 格式，包含以下字段：
linkedin_post_1 (一段引人深思的专业长文，带钩子), 
linkedin_post_2 (提取长文中的数据或案例，结构化展示), 
twitter_thread (3-5条连贯的推文，用编号表示), 
tiktok_hook (极具吸引力的视频开头), 
tiktok_visual (画面拍摄建议), 
tiktok_script (口播文案，口语化), 
tiktok_cta (行动号召), 
xiaohongshu_title (带emoji的爆款标题), 
xiaohongshu_body (结构清晰、带emoji的种草文案), 
xiaohongshu_images (建议的3-4张配图画面)"""

    user_prompt = f"请将以下长文重组为多平台矩阵内容：\n\n{source_text[:3000]}..." # 限制长度避免超token
    
    return call_llm(system_prompt, user_prompt, json_mode=True)

def main():
    parser = argparse.ArgumentParser(description="智能内容重组引擎 (Content Repurposer - LLM Powered)")
    parser.add_argument("--source", required=True, help="源长文的文件路径 (如: blog_post.md)")
    parser.add_argument("--output", help="输出文件名")
    
    args = parser.parse_args()
    
    print(f"\n🔄 正在启动 AI 内容重组引擎...")
    print(f"📄 读取源文件: {args.source}")
    
    source_text = read_source_file(args.source)
    if not source_text:
        return
        
    print(f"🧠 正在调用 LLM 进行多维拆解重组...")
    data = repurpose_content(source_text)
    
    if not data:
        print("❌ LLM 生成失败。")
        return
        
    data["source_file"] = os.path.basename(args.source)
    data["date"] = datetime.now().strftime("%Y-%m-%d")
    
    result_doc = REPURPOSE_TEMPLATE.format(**data)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(result_doc)
        print(f"\n✅ 内容重组矩阵已生成并保存至: {args.output}")
    else:
        print("\n" + "="*60)
        print(result_doc)
        print("="*60)

if __name__ == "__main__":
    main()
