#!/usr/bin/env python3
"""
冷邮件序列生成器 - 自动生成高转化率的B2B邮件自动化工作流 (Drip Campaigns)
模拟 Demand Generation Manager 的职能
"""

import argparse
from datetime import datetime

EMAIL_SEQUENCE_TEMPLATE = """
# 📧 B2B 高转化冷邮件序列 (Cold Email Sequence)

**目标人群 (Target)**: {target}
**阶段数量 (Stages)**: {stages}
**发送节奏 (Cadence)**: Day 1 -> Day 4 -> Day 9 -> Day 16 -> Day 25

---

## 阶段 1: 破冰与价值抛出 (The Hook)
**发送时间**: Day 1
**目标**: 引起注意，指出痛点，但不急于推销。

**Subject**: {subject_1}
**Body**:
Hi [First Name],

I noticed you're leading the sourcing efforts at [Company Name]. 

Many [Target Role]s I speak with in the [Industry] space are currently struggling with [Pain Point 1] and [Pain Point 2]. Is this something your team is dealing with right now?

We recently helped [Similar Company] solve exactly this, resulting in a [Specific Metric/ROI].

If you're open to it, I'd love to share a quick 2-page case study on how they did it. 

Best,
[Your Name]

---

## 阶段 2: 案例与社会证明 (The Proof)
**发送时间**: Day 4 (如果没有回复)
**目标**: 提供价值，建立信任。

**Subject**: Re: {subject_1}
**Body**:
Hi [First Name],

Just bubbling this up. 

I know how busy things get, so I’ll keep it brief. Here is the case study I mentioned about how [Similar Company] achieved [Specific Metric/ROI] by switching to our [Product/Solution].

[Link to Case Study]

The most interesting part is how they managed to [Overcome Objection/Challenge] in just [Timeframe].

Worth a 10-minute chat next Tuesday to see if this could work for [Company Name]?

Cheers,
[Your Name]

---

## 阶段 3: 价值微承诺 (The Soft Ask)
**发送时间**: Day 9 (如果没有回复)
**目标**: 降低门槛，提供免费且极具价值的东西。

**Subject**: Quick question regarding [Topic]
**Body**:
Hi [First Name],

I haven't heard back, so I'm assuming timing might not be right for a call.

Instead, I'd love to send you a complimentary [Lead Magnet: e.g., Material Sample Book / Industry Report] that covers [Specific Value]. No strings attached.

Where is the best address to send this?

Best,
[Your Name]

---

## 阶段 4: 异议处理与差异化 (The Differentiator)
**发送时间**: Day 16 (如果没有回复)
**目标**: 预判客户的顾虑，展示独特优势。

**Subject**: How [Company Name] compares to traditional options
**Body**:
Hi [First Name],

One thing I often hear from [Target Role]s is that switching suppliers/tools feels like too much of a risk right now.

I completely understand. That's why we built our process to be 100% risk-free. Unlike [Competitor/Traditional Way], we offer:
1. [Advantage 1: e.g., Free prototyping within 3 days]
2. [Advantage 2: e.g., No minimum order quantity for the first batch]

Would it make sense to explore this on a quick 5-minute intro call?

Thanks,
[Your Name]

---

## 阶段 5: 分手邮件 (The Break-up)
**发送时间**: Day 25 (如果没有回复)
**目标**: 利用损失厌恶(FOMO)促使最后一次回复，或者优雅退出。

**Subject**: Closing the loop
**Body**:
Hi [First Name],

I’ve reached out a few times about helping [Company Name] with [Pain Point/Goal], but haven’t heard back. 

Usually, this means it’s not a priority right now, or you’re already working with someone great. Either way is completely fine!

I’ll stop reaching out for now. If things change in the future, feel free to reply to this email or find me on LinkedIn.

Wishing you and the team at [Company Name] a great rest of the year.

Best regards,
[Your Name]

---
*Generated by Super Marketing Pro v2.0 at {date}*
"""

def generate_sequence(target, stages):
    """生成邮件序列"""
    
    # 动态生成第一封邮件的主题
    if "sourcing" in target.lower() or "procurement" in target.lower():
        subject_1 = "Idea for [Company Name]'s material sourcing"
    elif "marketing" in target.lower():
        subject_1 = "Growth strategy for [Company Name]"
    elif "ceo" in target.lower() or "founder" in target.lower():
        subject_1 = "Scaling [Company Name] efficiently"
    else:
        subject_1 = "Quick question for [First Name]"
        
    context = {
        "target": target,
        "stages": stages,
        "subject_1": subject_1,
        "date": datetime.now().strftime("%Y-%m-%d")
    }
    
    # 简单的阶段裁剪（根据要求的stages数量）
    full_doc = EMAIL_SEQUENCE_TEMPLATE.format(**context)
    
    if stages < 5:
        # 简单粗暴地按阶段截断（仅为演示逻辑）
        parts = full_doc.split("## 阶段 ")
        kept_parts = [parts[0]] + parts[1:stages+1]
        full_doc = "## 阶段 ".join(kept_parts) + "\n\n---\n*Generated by Super Marketing Pro v2.0*"
        
    return full_doc

def main():
    parser = argparse.ArgumentParser(description="冷邮件序列生成器 (Demand Gen Agent)")
    parser.add_argument("--target", required=True, help="目标决策者职位 (如: Procurement Manager)")
    parser.add_argument("--stages", type=int, default=5, choices=[3, 4, 5], help="邮件序列的阶段数 (默认: 5)")
    parser.add_argument("--output", help="输出文件名")
    
    args = parser.parse_args()
    
    print(f"\n📨 正在生成高转化冷邮件序列...")
    print(f"🎯 目标人群: {args.target}")
    print(f"📈 阶段数量: {args.stages} 步")
    
    sequence_doc = generate_sequence(args.target, args.stages)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(sequence_doc)
        print(f"\n✅ 邮件序列已生成并保存至: {args.output}")
    else:
        print("\n" + "="*60)
        print(sequence_doc)
        print("="*60)

if __name__ == "__main__":
    main()
