#!/usr/bin/env python3
"""
深度SEO集群分析器 - 自动生成 Topic Cluster 策略和长尾关键词矩阵
模拟 SEO Director 的职能
"""

import argparse
import json
from datetime import datetime
from llm_utils import call_llm

SEO_CLUSTER_TEMPLATE = """
# 🔍 SEO Topic Cluster 战略分析报告

**核心种子词 (Pillar Keyword)**: {seed_keyword}
**分析深度 (Depth)**: {depth}

---

## 🏛️ 支柱页面内容规划 (Pillar Page Strategy)
支柱页面是一篇 3000+ 字的终极指南，全面覆盖该主题的所有基础知识。

**建议标题 (H1)**: 
The Ultimate Guide to {seed_keyword} in 2025: Everything You Need to Know

**核心章节 (H2)**:
1. What is {seed_keyword}? (Definitions & Basics)
2. The Evolution of {seed_keyword} in the Industry
3. Key Benefits and ROI of Implementing {seed_keyword}
4. Common Challenges & How to Overcome Them
5. Top 5 Use Cases / Applications
6. Future Trends to Watch

---

## 🪐 子主题集群矩阵 (Topic Cluster Matrix)
这些是支持支柱页面的深度子文章，所有子文章都必须通过内部链接指向支柱页面。

### 集群 1: 成本与ROI类 (Bottom of Funnel - 高购买意图)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `{seed_keyword} cost analysis` | 比较/购买 | How Much Does {seed_keyword} Really Cost? A Breakdown | 中 |
| `ROI of {seed_keyword}` | 商业论证 | Measuring the ROI of {seed_keyword} for Your Business | 高 |
| `{seed_keyword} vs traditional alternatives` | 比较 | {seed_keyword} vs Traditional Methods: Which is Better? | 低 |

### 集群 2: 操作与指南类 (Middle of Funnel - 教育与培养)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `how to implement {seed_keyword}` | 学习/操作 | A Step-by-Step Guide to Implementing {seed_keyword} | 中 |
| `best practices for {seed_keyword}` | 优化 | 7 Best Practices for Maximizing {seed_keyword} Efficiency | 低 |
| `mistakes to avoid with {seed_keyword}` | 避坑 | The Top 5 Mistakes Companies Make with {seed_keyword} | 低 |

### 集群 3: 行业特定类 (Niche/Vertical - 精准流量)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `{seed_keyword} for manufacturing` | 行业应用 | Why Manufacturing is Rapidly Adopting {seed_keyword} | 中 |
| `{seed_keyword} compliance and regulations` | 风险规避 | Navigating Compliance When Using {seed_keyword} | 高 |

---

## 🔗 内部链接架构建议 (Internal Linking Architecture)

1. **Pillar to Cluster**: 支柱页面必须在相应的 H2 章节中链接到对应的子主题文章。
2. **Cluster to Pillar**: 每篇子主题文章的前 100 个单词内，必须包含指向支柱页面的精准锚文本 (Exact Match Anchor Text)。
3. **Cluster to Cluster**: 同一集群内的子文章，如果在逻辑上相关（例如成本分析和ROI计算），应当相互链接。

---
*Generated by Super Marketing Pro v2.0 at {date}*
"""

def generate_seo_cluster(seed_keyword, depth):
    """使用 LLM 生成SEO集群策略"""
    system_prompt = """你是一个顶级的 SEO 总监。你的任务是为一个给定的种子关键词生成 Topic Cluster (主题集群) 架构。
必须返回严格的 JSON 格式，包含以下字段：
seed_keyword, depth, 
h1_title, h2_1, h2_2, h2_3, h2_4, h2_5, h2_6,
cluster1_kw1, cluster1_intent1, cluster1_title1, cluster1_diff1,
cluster1_kw2, cluster1_intent2, cluster1_title2, cluster1_diff2,
cluster1_kw3, cluster1_intent3, cluster1_title3, cluster1_diff3,
cluster2_kw1, cluster2_intent1, cluster2_title1, cluster2_diff1,
cluster2_kw2, cluster2_intent2, cluster2_title2, cluster2_diff2,
cluster2_kw3, cluster2_intent3, cluster2_title3, cluster2_diff3,
cluster3_kw1, cluster3_intent1, cluster3_title1, cluster3_diff1,
cluster3_kw2, cluster3_intent2, cluster3_title2, cluster3_diff2
注意：长尾关键词必须高度具体、符合真实用户搜索习惯，重点包含长尾词。"""

    user_prompt = f"请为种子关键词 '{seed_keyword}' 生成主题集群，深度为: {depth}。"
    
    print(f"🧠 正在调用 LLM 分析种子关键词: '{seed_keyword}'...")
    data = call_llm(system_prompt, user_prompt, json_mode=True)
    
    if not data:
        print("⚠️ LLM 调用失败，使用本地降级数据...")
        context = {
            "seed_keyword": seed_keyword.title(),
            "depth": depth.upper(),
            "date": datetime.now().strftime("%Y-%m-%d")
        }
        return SEO_CLUSTER_TEMPLATE.format(**context)
        
    # 构建模板所需的上下文
    context = {
        "seed_keyword": data.get("seed_keyword", seed_keyword.title()),
        "depth": data.get("depth", depth.upper()),
        "date": datetime.now().strftime("%Y-%m-%d")
    }
    
    # 动态构建报告内容
    report = f"""# 🔍 SEO Topic Cluster 战略分析报告

**核心种子词 (Pillar Keyword)**: {context['seed_keyword']}
**分析深度 (Depth)**: {context['depth']}

---

## 🏛️ 支柱页面内容规划 (Pillar Page Strategy)
支柱页面是一篇 3000+ 字的终极指南，全面覆盖该主题的所有基础知识。

**建议标题 (H1)**: 
{data.get('h1_title', f'The Ultimate Guide to {seed_keyword}')}

**核心章节 (H2)**:
1. {data.get('h2_1', 'Introduction')}
2. {data.get('h2_2', 'Core Concepts')}
3. {data.get('h2_3', 'Benefits')}
4. {data.get('h2_4', 'Challenges')}
5. {data.get('h2_5', 'Use Cases')}
6. {data.get('h2_6', 'Future Trends')}

---

## 🪐 子主题集群矩阵 (Topic Cluster Matrix)

### 集群 1: 成本与ROI类 (Bottom of Funnel - 高购买意图)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `{data.get('cluster1_kw1', '')}` | {data.get('cluster1_intent1', '')} | {data.get('cluster1_title1', '')} | {data.get('cluster1_diff1', '')} |
| `{data.get('cluster1_kw2', '')}` | {data.get('cluster1_intent2', '')} | {data.get('cluster1_title2', '')} | {data.get('cluster1_diff2', '')} |
| `{data.get('cluster1_kw3', '')}` | {data.get('cluster1_intent3', '')} | {data.get('cluster1_title3', '')} | {data.get('cluster1_diff3', '')} |

### 集群 2: 操作与指南类 (Middle of Funnel - 教育与培养)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `{data.get('cluster2_kw1', '')}` | {data.get('cluster2_intent1', '')} | {data.get('cluster2_title1', '')} | {data.get('cluster2_diff1', '')} |
| `{data.get('cluster2_kw2', '')}` | {data.get('cluster2_intent2', '')} | {data.get('cluster2_title2', '')} | {data.get('cluster2_diff2', '')} |
| `{data.get('cluster2_kw3', '')}` | {data.get('cluster2_intent3', '')} | {data.get('cluster2_title3', '')} | {data.get('cluster2_diff3', '')} |

### 集群 3: 行业特定类 (Niche/Vertical - 精准流量)
| 长尾关键词 (Long-tail Keyword) | 搜索意图 | 建议文章标题 | 难度估算 |
|--------------------------------|----------|--------------|----------|
| `{data.get('cluster3_kw1', '')}` | {data.get('cluster3_intent1', '')} | {data.get('cluster3_title1', '')} | {data.get('cluster3_diff1', '')} |
| `{data.get('cluster3_kw2', '')}` | {data.get('cluster3_intent2', '')} | {data.get('cluster3_title2', '')} | {data.get('cluster3_diff2', '')} |

---

## 🔗 内部链接架构建议 (Internal Linking Architecture)

1. **Pillar to Cluster**: 支柱页面必须在相应的 H2 章节中链接到对应的子主题文章。
2. **Cluster to Pillar**: 每篇子主题文章的前 100 个单词内，必须包含指向支柱页面的精准锚文本 (Exact Match Anchor Text)。
3. **Cluster to Cluster**: 同一集群内的子文章，如果在逻辑上相关（例如成本分析和ROI计算），应当相互链接。

---
*Generated by Super Marketing Pro v3.1 (LLM Powered) at {context['date']}*
"""
    return report

def main():
    parser = argparse.ArgumentParser(description="SEO Topic Cluster 分析器 (SEO Director Agent)")
    parser.add_argument("--seed-keyword", required=True, help="核心种子关键词 (如: PU Leather, Marketing Automation)")
    parser.add_argument("--depth", choices=["basic", "deep"], default="deep", help="分析深度")
    parser.add_argument("--output", help="输出文件名")
    
    args = parser.parse_args()
    
    print(f"\n🕸️ 正在构建 SEO Topic Cluster 架构...")
    print(f"🔑 种子关键词: {args.seed_keyword}")
    print(f"🕳️ 分析深度: {args.depth}")
    
    seo_doc = generate_seo_cluster(args.seed_keyword, args.depth)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(seo_doc)
        print(f"\n✅ SEO集群策略已生成并保存至: {args.output}")
    else:
        print("\n" + "="*60)
        print(seo_doc)
        print("="*60)

if __name__ == "__main__":
    main()
