#!/usr/bin/env python3
"""
战略构建器 - 自动生成 ICP (理想客户画像) 和品牌信息架构
模拟 CMO/VP of Marketing 的战略大脑
集成 LLM 引擎，实现真正的智能分析
"""

import argparse
import json
from datetime import datetime
from llm_utils import call_llm

# 本地降级模板（当无 API Key 时使用）
FALLBACK_DATA = {
    "industry": "B2B",
    "company_size": "中大型企业",
    "geography": "全球市场",
    "revenue": "$5M+",
    "technographics": "数字化转型中",
    "buyer_role_1": "决策者/CEO/VP",
    "buyer_kpi_1": "ROI，降本增效",
    "buyer_pain_1": "效率低下，成本高昂",
    "buyer_objection_1": "预算限制，切换成本高",
    "buyer_role_2": "业务主管/总监",
    "buyer_kpi_2": "团队效率，目标达成",
    "buyer_pain_2": "工具难用，流程繁琐",
    "buyer_objection_2": "学习曲线长，团队抗拒",
    "uvp": "提供高效的产品/服务，解决行业痛点，实现核心价值。",
    "elevator_pitch": "我们帮助目标客户解决核心痛点。通过独特方案，客户能够获得具体收益。",
    "pillar_1_name": "核心优势 1",
    "pillar_1_desc": "描述优势 1",
    "pillar_1_proof": "数据/案例证明",
    "pillar_2_name": "核心优势 2",
    "pillar_2_desc": "描述优势 2",
    "pillar_2_proof": "数据/案例证明",
    "pillar_3_name": "核心优势 3",
    "pillar_3_desc": "描述优势 3",
    "pillar_3_proof": "数据/案例证明"
}

ICP_TEMPLATE = """
# 🎯 理想客户画像 (Ideal Customer Profile - ICP)

## 🏢 目标企业特征 (Firmographics)
- **目标行业**: {industry}
- **公司规模**: {company_size}
- **地理位置**: {geography}
- **营收规模**: {revenue}
- **技术栈/特征**: {technographics}

## 👤 关键决策者 (Buyer Personas)
### 1. 经济买家 (Economic Buyer)
- **职位**: {buyer_role_1}
- **核心KPI**: {buyer_kpi_1}
- **最大痛点**: {buyer_pain_1}
- **主要异议**: {buyer_objection_1}

### 2. 技术/使用者买家 (Technical/User Buyer)
- **职位**: {buyer_role_2}
- **核心KPI**: {buyer_kpi_2}
- **最大痛点**: {buyer_pain_2}
- **主要异议**: {buyer_objection_2}

## 💡 品牌信息架构 (Messaging Framework)

### 核心价值主张 (Unique Value Proposition)
"{uvp}"

### 电梯演讲 (Elevator Pitch - 30秒)
"{elevator_pitch}"

### 核心信息支柱 (Key Messaging Pillars)
1. **{pillar_1_name}**: {pillar_1_desc}
   - *支撑证据*: {pillar_1_proof}
2. **{pillar_2_name}**: {pillar_2_desc}
   - *支撑证据*: {pillar_2_proof}
3. **{pillar_3_name}**: {pillar_3_desc}
   - *支撑证据*: {pillar_3_proof}

---
*Generated by Super Marketing Pro v3.0 (LLM Powered) at {date}*
"""

def build_strategy_with_llm(industry, product):
    """使用 LLM 构建战略"""
    system_prompt = """你是一个顶级的 B2B CMO (首席营销官)。你的任务是为特定行业和产品制定极度精准的理想客户画像(ICP)和品牌信息架构。
必须返回严格的 JSON 格式，包含以下字段：
industry, company_size, geography, revenue, technographics, 
buyer_role_1, buyer_kpi_1, buyer_pain_1, buyer_objection_1, 
buyer_role_2, buyer_kpi_2, buyer_pain_2, buyer_objection_2, 
uvp, elevator_pitch, 
pillar_1_name, pillar_1_desc, pillar_1_proof, 
pillar_2_name, pillar_2_desc, pillar_2_proof, 
pillar_3_name, pillar_3_desc, pillar_3_proof"""

    user_prompt = f"请为以下业务生成营销战略架构：\n目标行业：{industry}\n核心产品/服务：{product}\n请确保内容极度具体、专业，拒绝空话套话。"
    
    result = call_llm(system_prompt, user_prompt, json_mode=True)
    return result

def main():
    parser = argparse.ArgumentParser(description="营销战略与ICP构建器 (CMO Agent - LLM Powered)")
    parser.add_argument("--industry", required=True, help="目标行业 (如: Footwear Material, SaaS)")
    parser.add_argument("--product", required=True, help="核心产品/服务名称")
    parser.add_argument("--export-format", choices=["md", "json"], default="md", help="导出格式")
    parser.add_argument("--output", help="输出文件名")
    
    args = parser.parse_args()
    
    print(f"\n🧠 正在启动 AI 战略引擎...")
    print(f"🎯 分析行业: {args.industry}")
    print(f"📦 核心产品: {args.product}")
    
    # 尝试使用 LLM 生成
    data = build_strategy_with_llm(args.industry, args.product)
    
    if not data:
        print("⚠️ 切换到本地降级模式...")
        data = FALLBACK_DATA.copy()
        data["industry"] = args.industry
        data["uvp"] = data["uvp"].replace("产品/服务", args.product)
    
    data["date"] = datetime.now().strftime("%Y-%m-%d")
    strategy_doc = ICP_TEMPLATE.format(**data)
    
    if args.output:
        if args.export_format == "json":
            with open(args.output, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
        else:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(strategy_doc)
        print(f"\n✅ 战略架构已生成并保存至: {args.output}")
    else:
        print("\n" + "="*60)
        print(strategy_doc)
        print("="*60)

if __name__ == "__main__":
    main()
